### ISSUE TITLE
Optimize background image

### ISSUE THREAD

**Issue by colinsullivan** [concertsoundorganizer/Concert#17]
jquery plugin to generate noise:
https://github.com/DanielRapp/Noisy/tree/master/example

It would also be nice to get that curve in there from Craig's original design https://docs.google.com/leaf?id=0By64YSWDH2DYZmNjNzZjNDktZjk4MC00NjIwLTkwN2UtNmY5YzRlNjBiMDkw&hl=en&authkey=CKX4-_UG.  I see a few ways of doing this.

One:
Make background of all pages two divs, and somehow make one of them have really large rounded corners.

two: 
canvas

**Comment by colinsullivan** [comment]
@floating: Craig, have you done this?

**Comment by floating** [comment]
Yes, but i'm not sure the background glare is up to par yet. I'll open another issue detailing this.
