### ISSUE TITLE
Favicon gets stretched to a square in Safari

### ISSUE THREAD

**Issue by colinsullivan** [concertsoundorganizer/Concert#18]
https://docs.google.com/leaf?id=0B1uQWmnCzsgiMjJkZjYxY2UtNDYzOC00MmYzLThiM2YtOGUwN2M5OGY2ZGE3&hl=en&authkey=CIecorUI

**Comment by colinsullivan** [comment]
Also in Firefox.

**Comment by floating** [comment]
It's just using the logo file for the favicon right now. I will output a proper favicon with square proportions soon.

**Comment by floating** [comment]
fixed in loggedin branch
