### ISSUE TITLE
Tag Icon

### ISSUE THREAD

**Issue by colinsullivan** [concertsoundorganizer/Concert#28]
We need a tag icon in the static/ directory.  

Sample icon page:
https://docs.google.com/leaf?id=0B1uQWmnCzsgiMTllODQzODYtMzA2Ny00MzcyLWIwZjktZWRlZjBlM2FiNDRl&hl=en&authkey=CPaJpeYM

Icon render from Chris:
https://docs.google.com/leaf?id=0B64dcU7fjF5MMGZmMTc0MzktNmZhMC00MGYxLWI0NGYtNGMxZTBiNWE0MmI2&hl=en&authkey=CN3wjNAN

**Comment by floating** [comment]
looks like this is done
