### ISSUE TITLE
Waveform interaction behavior

### ISSUE THREAD

**Issue by colinsullivan** [concertsoundorganizer/Concert#31]
Playing around with the waveform, I'm beginning to think that we should do things a little differently.

Currently, we have two visible "zones" in the detail waveform viewer.  One is the area where the waveform is, and the other is the bottom, where the timecode is.  Currently, clicking in either of these places has the same functionality:
- If there was a highlight, the highlight will be cleared
- The playhead will move to the location that was clicked

Because of this behavior, I see a few use cases with no solutions:
1. We are listening to a highlighted section and want to skip to a part in the middle of this section without losing the highlight.
2. We are listening to a highlighted section, and want to clear the highlight without moving the playhead.

My ideas:
- Click on the waveform area
  - If there was a highlight, it will be cleared.
- Click on the timecode area
  - Playhead moves to that position.
  - If the area chosen is outside the highlighted area
    - Clear highlight?
    - Don't allow this, just jump back to beginning of highlight until highlight is cleared?

This is only for the `DetailWaveformPanel` however, we would still need to figure out what to do on the `OverviewWaveformPanel`.

**Comment by amywieliczka** [comment]
If we consider highlighting behavior from within a sequence:
- The user highlights a section of the waveform image, prompting segment
  creation with an editable name field & draggable segment handles.
- The user selects a segment (whether from an event feed or from the audio
  list on the organize page) prompting the waveforms to highlight a section of
  the waveform image with an editable name field & draggable segment handles.

In both these cases, the highlighted area is being treated as a 'segment',
in the event of recent creation, perhaps the user hasn't explicitly defined
the segment, but it is still being treated as a segment. From this line of
thought, clearing a highlighted section on the waveform image involves
deleting a segment (perhaps using a deletion icon near the name or duration
information, or near the tags area), or selecting the segment's parent audio
file.

Clicking on the waveform image would then only move the playhead (turning
off the segment loop if the click occurs outside the highlight, and vice
versa if it occurs inside the highlight), without interacting with the
highlight at all.

We had also talked about dragging behavior on the part of the playhead that
extends into the timecode zone (once it is two canvas elements and not one
div element).

Maybe I'm missing the reason why you would want to clear a segment without
deleting it - wouldn't that be the same as selecting the parent audio file?

-Amy

**Comment by colinsullivan** [comment]
Yes, I see clearing the highlight as the same as selecting the parent audio file.  

I am comfortable with the functionality that you described.  I also cannot think of a reason for clearing the highlight, and if you really wanted to you could just click on the segment's parent `AudioFile` object (a link to which could be on the top right of the `DetailWaveformPanel` _i.e. 00:03:24 of myparent_).

So, the functionality should be as follows:
- Clicking inside the highlight moves the playhead, keeps audio loop on.
- Clicking outside the highlight moves the playhead, turning audio loop off.

## Highlight remains in either case.

Colin
colin-sullivan.com

**Comment by colinsullivan** [comment]
Works
