### ISSUE TITLE
Autoscroll should put some buffer on the left

### ISSUE THREAD

**Issue by colinsullivan** [concertsoundorganizer/Concert#37]
Currently, when an audio segment is selected, the left side of the highlight is adjacent to the left side of the viewer "window".  I think there should be some buffer there so you can see a little before the highlight.

**Comment by amywieliczka** [comment]
Only on segment selection? Or also when autoscroll engages? (Placing buffer before the current position of the playhead.)

**Comment by colinsullivan** [comment]
Anytime there is an area of interest (i.e. a highlight), and we are scrolling to it, we should be able to see the left side of it.

**Comment by colinsullivan** [comment]
Yea, a buffer next to the playhead would be cool I think.

**Comment by amywieliczka** [comment]
works
